title: "n8slab"
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  n8's personal blog

url: "https://n8slab.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Projects
      url: /projects
    - text: Connect
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: newprofilepic.jpeg
author: Nate Equan
author_quickbio: Software Developer, QA Enthusiast, Cybersecurity Engineer
author_bio: Versatile software engineer with 6+ years of industry experience designing and implementing secure, high-quality software and cybersecurity solutions. Proven track record of building and optimizing DevOps frameworks by integrating automated tests and security controls into CI/CD pipelines, ensuring Quality Assurance and Data Security at scale. Subject matter expert in developing comprehensive test plans to validate functional and security requirements, enhancing system reliability and mitigating risk. Demonstrated success in leading testing efforts across the SDLC for multiple, concurrent projects, collaborating with cross-functional teams to deliver secure, on-time solutions that meet stakeholder expectations, organizational objectives, and compliance with industry standards.
author_email: "nate.equan@gmail.com"
author_location: Charlotte, NC
author_website_url: ""
typewrite-text: welcome to the lab 💻...
hero_cover_img: homepage_banner.jpeg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences (About Page)
author_work_experiences:
            - company_name: Awards North
              company_logo: anlogo1000x1000_nobg.png
              company_url: https://awardsnorth.com
              designation: Manager/Production Engineer
              description: Lead the completion of 800+ client projects grossing over $125K in sales within a 11-month period, maintaining strict adherence to budgetary constraints and timelines. Designed custom digital drafts using Adobe and Corel graphics software, configuring and operating five industrial laser systems to deliver high-quality, personalized client products
              visibility: true
            - company_name: Delta Air Lines, Inc.
              company_logo: delta_logo_nobg.png
              company_url: https://delta.com
              designation: Senior Software Engineer, QA
              description: Led and coordinated the software QA initiatives across 3 cross-functional teams for the successful delivery of 6 new Enterprise software products, and maintenance of our software product suite containing 30+ web apps. Collaborated with developers, product owners, and stakeholders to improve user experience and mitigate vulnerabilities and defects
              visibility: true
            - company_name: Fidelity Investments
              company_logo: Fidelity+Investments+Logo.png
              company_url: https://fidelity.com
              designation: Software Engineer II, QA 
              description: Piloted the restructure of QA/testing framework by designing & executing 800+ manual and automated end-to-end test cases for our cryptographic signing/key management APIs, increasing our test coverage by over 500% to secure over $4 Billion in company and client assets
              visibility: true
            - company_name: Fidelity Investments
              company_logo: Fidelity+Investments+Logo.png
              company_url: https://fidelity.com
              designation: Systems Analyst Intern
              description: Delivered technical solutions for vendor PaaS platform and SaaS products, offering business analysts improved tools for use in organizing data and streamlining client communications
              visibility: true

# Education
author_education_details:
              - college_logo: uncc_logo_nobg.png
                college_name: University of North Carolina at Charlotte
                college_url: https://uncc.edu
                college_degree: B.S. Computer Science
                graduation_date: May 2019
                description: Concentration in Cybersecurity
                visibility: true
              - college_logo: uncc_logo_nobg.png
                college_name: University of North Carolina at Charlotte
                college_url: https://uncc.edu
                college_degree: B.A. Criminal Justice
                graduation_date: May 2019
                description:
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: 
                project_title: 
                project_description: 
                project_url: 
                visibility: false
              - project_thumbnail: 
                project_title: 
                project_description: 
                project_url: 
                visibility: false

# social links
github_username:  n8slab
# facebook_username: johndoe
linkedin_username: nateequan
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: 
# hyvor_talk_website_id: 

# wakatime username (coding activity)
wakatime_username: n8slab

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
